# 이 디렉터리에 있는 move package의 정보를 기입
[package]
# 패키지명과 버전 기입
name = "ArgumentExample"
version = "0.0.0"

# 사용하는 주소들을 변수값으로 사용할 수 있도록 함
[addresses]
# default profile alias 사용
deploy_address = "_"

# 사용할 move library 가져오기
[dependencies]
# Aptos core안에 저장되어있는 aptos move 라이브러리 사용
AptosFramework = { local = "../../framework/aptos-framework"}